root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "tmp/main"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = "white"

[misc]
clean_on_exit = true