version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=gamification-platform
      - DB_USER=root
      - DB_PASSWORD=password

  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gamification-platform
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

volumes:
  db_data: