basePath: /api/v1
definitions:
  handlers.APIError:
    properties:
      createdAt:
        type: string
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
info:
  contact: {}
  description: This is a api server for gamification platform.
  title: Gamification Platform API
  version: "1.0"
paths:
  /testapi/get-string-by-int/{some_id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: We need ID!!
          schema:
            $ref: '#/definitions/handlers.APIError'
        "404":
          description: Can not find ID
          schema:
            $ref: '#/definitions/handlers.APIError'
      summary: Add a new pet to the store
swagger: "2.0"
